name: yamllint
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  create:
jobs:
  ci:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    needs: notify
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Run yamllint on actions
        run: |
            yamllint --format github github-actions
